# Generated by Django 5.1.2 on 2024-10-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pest',
            new_name='Pets',
        ),
    ]
